### ISSUE TITLE
Ornate Chest and Trog Chest Filter Only

### ISSUE THREAD

**Issue by EremesNG** [exp111/OutwardStuff#2]
Hi.

Is there a way to only randomize the [Ornate Chest](https://outward.fandom.com/wiki/Ornate_Chest) and the [Trog Chest](https://outward.fandom.com/wiki/Trog_Chest)?

Sometimes in a normal chest a very powerful weapon will be randomized and I would like to avoid that.

Awesome mod ❤️

**Comment by exp111** [comment]
Added in 93462d8. 
If you find any chest that isn't randomized or should be randomized (because i needed to add a check dependant on the ID and i might have missed some), please notify me.

Uploaded to Thunderstore as 1.1.6
