### ISSUE TITLE
Hostile enemies naked and unable to attack

### ISSUE THREAD

**Issue by EremesNG** [exp111/OutwardStuff#3]
I have an issue with Randomizer, all hostile humans don't have weapons and are naked and unable to attack.

Config:
![ConfigMod](https://i.imgur.com/yq9CfY6.png)

**Comment by EremesNG** [comment]
I think this function is the issue [StartingEquipmentInitPatch](https://github.com/exp111/OutwardStuff/blob/master/Randomizer/Randomizer.cs#L605)

The function expects that weapons and armor are randomized but when not, it deletes the original item, so I put this lines to try and it works on my tests.
![IfsImage](https://i.imgur.com/7BeozLH.png)

**Comment by exp111** [comment]
Oh yeah that would make sense. I'll add those when i get to it

**Comment by exp111** [comment]
Uploaded on Thunderstore as version 1.1.7
